#!/usr/bin/env python3
# Copyright 2026 Jose Laruta
"""ros2 run entry point for the Python rate_listener solution."""

from tut01_nodes_solution.rate_listener import main

if __name__ == '__main__':
    main()
